# fly.toml app configuration file generated for spring-grass-8623 on 2023-05-29T08:34:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-grass-8623"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[[services]]
  protocol = ""
  internal_port = 3000
  processes = ["app"]
